name: Unreal Engine CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted  # your runner (AT-7105)
    defaults:
      run:
        shell: cmd   # 👈 force CMD for every step

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Unreal project
        run: |
          echo Building Unreal project...
          "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\Build.bat" ^
            MyProject4Editor Win64 Development ^
            -Project="%CD%\MyProject4.uproject" -WaitMutex -NoHotReload

      - name: Package Game
        run: |
          "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
            -project="%CD%\MyProject4.uproject" -noP4 -platform=Win64 ^
            -clientconfig=Development -serverconfig=Development ^
            -cook -allmaps -build -stage -pak -archive -archivedirectory="%CD%\BuildOutput"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unreal-Build
          path: BuildOutput
