name: Unreal Engine Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android-build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # -------- Build (Android Game Target) --------
      - name: Build Unreal project (Android)
        run: |
          echo Building Unreal project (Android Game)...
          "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\Build.bat" ^
            MyProject4 Android Development ^
            -Project="%CD%\MyProject4.uproject" -WaitMutex -NoHotReload

      # -------- Package (APK) --------
      - name: Package Game (Android - APK)
        run: |
          call "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
            -project="%CD%\MyProject4.uproject" -noP4 -platform=Android ^
            -clientconfig=Development -serverconfig=Development ^
            -cook -allmaps -build -stage -pak -archive -archivedirectory="%CD%\BuildOutput\Android" ^
            -package -apk

      # -------- Upload Artifact --------
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: Unreal-Build-Android
          path: BuildOutput/Android
